import type { User, Challenge, Notification } from '@/types';
import { ChallengeCategory, ChallengeDifficulty, ChallengeStatus } from '@/types';

// ─── Usuarios ────────────────────────────────────────────────────────────────

export const mockUser: User = {
  id: '1',
  name: 'Andrea Corrales',
  email: 'andrea@BingoChallenge.com',
  password: 'user123',
  role: 'user',
  avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
  level: 12,
  points: 2450,
  badges: [
    {
      id: '1',
      name: 'Corredor Inicial',
      description: 'Completaste tu primer reto de running',
      icon: '🏃',
      earnedAt: new Date('2024-01-15'),
      rarity: 'common',
    },
    {
      id: '2',
      name: 'Maratonista',
      description: 'Completaste 10 retos de running',
      icon: '🏅',
      earnedAt: new Date('2024-01-20'),
      rarity: 'rare',
    },
  ],
  completedChallenges: 15,
  activeChallenges: 3,
};

export const adminUser: User = {
  id: 'admin-1',
  name: 'Admin Sport',
  email: 'admin@sport.com',
  password: 'admin123',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?w=400',
  level: 99,
  points: 0,
  badges: [],
  completedChallenges: 0,
  activeChallenges: 0,
};

export const USERS_DB: User[] = [mockUser, adminUser];

// ─── Pool global de retos (todos los disponibles) ───────────────────────────

export const ALL_CHALLENGES: Challenge[] = [
  // RUNNING
  {
    id: '1',
    title: '111 mts.de desnivel positivo',
    description: 'Corre al menos 5km cada día durante 30 días consecutivos. Mejora tu resistencia cardiovascular y fortalece tus piernas.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 500,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1234,
    icon: '🏃',
    color: '#FF5327',
    images: [
      'https://pedalia.cc/wp-content/uploads/2018/05/desnivel-positivo-597x1024.jpg',
      'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400',
    ],
    tasks: [
      { id: '1-1', title: 'Día 1: 5km', description: 'Corre 5 kilómetros', completed: false, photoRequired: true },
      { id: '1-2', title: 'Día 2: 5km', description: 'Corre 5 kilómetros', completed: false, photoRequired: true },
      { id: '1-3', title: 'Día 3: 7km', description: 'Aumenta a 7 kilómetros', completed: false, photoRequired: true },
    ],
  },
  {
    // FIX: status → NOT_STARTED, progress → 0, tareas sin completed ni completedAt,
    // y photoRequired: true en al menos una tarea para habilitar subida de foto
    id: '2',
    title: 'Corre con medias disparejas',
    description: 'Incrementa tus flexiones progresivamente durante 21 días. De 10 a 100 flexiones diarias.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 300,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 856,
    icon: '💪',
    color: '#FC0230',
    images: [
      'https://www.chilevision.cl/chilevision/site/artic/20220321/imag/foto_0000000120220321181059/Monica_Rincon.jpg',
    ],
    tasks: [
      { id: '2-1', title: 'Semana 1: 10-20 flexiones', description: '', completed: false, photoRequired: true },
      { id: '2-2', title: 'Semana 2: 30-50 flexiones', description: '', completed: false, photoRequired: false },
      { id: '2-3', title: 'Semana 3: 60-100 flexiones', description: '', completed: false, photoRequired: false },
    ],
  },
  {
    id: '3',
    title: 'Cadencia promedio 175',
    description: 'Practica yoga cada mañana durante 14 días. Mejora tu flexibilidad y encuentra paz mental.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 250,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 2341,
    icon: '🧘',
    color: '#10B981',
    images: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400',
    ],
    tasks: [
      { id: '3-1', title: '5 posturas básicas', description: 'Aprende las posturas fundamentales', completed: false, photoRequired: true },
      { id: '3-2', title: 'Sesión de 20 min', description: 'Practica 20 minutos diarios', completed: false, photoRequired: false },
    ],
  },
  {
    id: '4',
    title: '+3 actividades en una semana',
    description: 'Recorre 100km en bicicleta durante 2 semanas. Explora tu ciudad sobre ruedas.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 400,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 678,
    icon: '🚴',
    color: '#3B82F6',
    images: [
      'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400',
    ],
    tasks: [
      { id: '4-1', title: '0-25km completados', description: '', completed: false, photoRequired: true },
      { id: '4-2', title: '25-50km completados', description: '', completed: false, photoRequired: true },
      { id: '4-3', title: '50-75km completados', description: '', completed: false, photoRequired: true },
      { id: '4-4', title: '75-100km completados', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    // FIX: photoRequired: true en la primera tarea para habilitar subida de foto
    id: '5',
    title: 'Foto de 3 tenis verdes',
    description: 'Nada 500m 3 veces por semana durante un mes. Técnica y resistencia acuática.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 350,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 445,
    icon: '🏊',
    color: '#06B6D4',
    images: [
      'https://contents.mediadecathlon.com/p2970586/k$6a9a98b3d848089bfe0c7d7bfb7160a5/tenis-de-running-asics-dynablast-5-ligereza-y-reactividad.jpg',
    ],
    tasks: [
      { id: '5-1', title: 'Semana 1-2: 12 sesiones', description: '', completed: false, photoRequired: true },
      { id: '5-2', title: 'Semana 3-4: 12 sesiones', description: '', completed: false, photoRequired: false },
    ],
  },
  {
    id: '6',
    title: 'Carril 6 en la pista',
    description: 'Sesiones intensas de 20 minutos, 5 días a la semana. Quema grasa y gana resistencia.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 600,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 923,
    icon: '🔥',
    color: '#F59E0B',
    images: [
      'https://previews.123rf.com/images/wutthichaic/wutthichaic1405/wutthichaic140500078/28701640-athletics-track-with-white-lane-number.jpg',
    ],
    tasks: [
      { id: '6-1', title: 'Semana 1: 5 sesiones', description: 'Burpees, sprints, plancha', completed: false, photoRequired: true },
      { id: '6-2', title: 'Semana 2: 5 sesiones', description: 'Aumenta intensidad', completed: false, photoRequired: true },
      { id: '6-3', title: 'Semana 3: 5 sesiones', description: 'Máximo esfuerzo', completed: false, photoRequired: true },
    ],
  },
  {
    // FIX: tasks con photoRequired: true — ya no cae en hasNoTasks
    id: '7',
    title: 'FC promedio < 150',
    description: 'Rutina de 10 minutos de estiramientos. Mejora la postura y relaja los músculos tensos.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 200,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1100,
    icon: '🤸',
    color: '#8B5CF6',
    images: [
      'https://i0.wp.com/elcardiologoencasa.com/wp-content/uploads/2014/11/Frecuencia-cariaca3.jpg',
    ],
    tasks: [
      { id: '7-1', title: 'Completar rutina', description: '10 minutos de estiramientos', completed: false, photoRequired: true },
    ],
  },
  {
    // FIX: tasks con photoRequired: true — ya no cae en hasNoTasks
    id: '8',
    title: 'Un ave en la ruta',
    description: 'Comienza con 20 sentadillas y aumenta la cantidad diariamente. Fortalece piernas y glúteos.',
    category: ChallengeCategory.RUNNING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 450,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 800,
    icon: '🦵',
    color: '#EC4899',
    images: [
      'https://cdn0.expertoanimal.com/es/posts/3/3/8/caracteristicas_de_las_aves_24833_orig.jpg',
    ],
    tasks: [
      { id: '8-1', title: 'Completar desafío', description: 'Aumenta sentadillas cada día', completed: false, photoRequired: true },
    ],
  },
  // GYM
  {
    id: 'g-1',
    title: 'Desafío de Flexiones',
    description: 'Incrementa tus flexiones progresivamente durante 21 días.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 300,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 856,
    icon: '💪',
    color: '#FC0230',
    images: ['https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=400'],
    tasks: [
      { id: 'g-1-1', title: 'Semana 1: 10-20', description: '', completed: false, photoRequired: true },
      { id: 'g-1-2', title: 'Semana 2: 30-50', description: '', completed: false, photoRequired: false },
      { id: 'g-1-3', title: 'Semana 3: 60-100', description: '', completed: false, photoRequired: false },
    ],
  },
  {
    id: 'g-2',
    title: 'Entrenamiento HIIT',
    description: 'Sesiones intensas de 20 minutos, 5 días a la semana.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 600,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 923,
    icon: '🔥',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400'],
    tasks: [
      { id: 'g-2-1', title: 'Semana 1: 5 sesiones', description: '', completed: false, photoRequired: true },
      { id: 'g-2-2', title: 'Semana 2: 5 sesiones', description: '', completed: false, photoRequired: false },
      { id: 'g-2-3', title: 'Semana 3: 5 sesiones', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'g-3',
    title: 'Desafío de Sentadillas',
    description: 'Comienza con 20 sentadillas y aumenta la cantidad diariamente.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 450,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 800,
    icon: '🦵',
    color: '#EC4899',
    images: [],
    tasks: [
      { id: 'g-3-1', title: 'Completar desafío', description: 'Aumenta sentadillas cada día', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'g-4',
    title: 'Boxeo Fitness',
    description: 'Tres sesiones de boxeo a la semana durante 3 semanas.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 420,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 730,
    icon: '🥊',
    color: '#FC0230',
    images: ['https://images.unsplash.com/photo-1615117950136-afcc0ad05a28?w=400'],
    tasks: [
      { id: 'g-4-1', title: 'Semana 1: 3 sesiones', description: 'Técnica básica', completed: false, photoRequired: true },
      { id: 'g-4-2', title: 'Semana 2: 3 sesiones', description: 'Combos', completed: false, photoRequired: false },
      { id: 'g-4-3', title: 'Semana 3: 3 sesiones', description: 'Sparring suave', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'g-5',
    title: 'Crossfit Básico',
    description: '5 sesiones de crossfit para principiantes.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 480,
    duration: 10,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 560,
    icon: '🏋️',
    color: '#EC4899',
    images: ['https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400'],
    tasks: [
      { id: 'g-5-1', title: 'Sesión 1: Intro', description: '', completed: false, photoRequired: false },
      { id: 'g-5-2', title: 'Sesión 2-3', description: '', completed: false, photoRequired: true },
      { id: 'g-5-3', title: 'Sesión 4-5', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'g-6',
    title: 'Dominadas x30',
    description: 'Llega a 10 dominadas consecutivas en 3 semanas.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 500,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 340,
    icon: '🔝',
    color: '#FC0230',
    images: ['https://images.unsplash.com/photo-1598971457999-ca4ef48a9a71?w=400'],
    tasks: [
      { id: 'g-6-1', title: 'Semana 1: negativas', description: '', completed: false, photoRequired: true },
      { id: 'g-6-2', title: 'Semana 2: asistidas', description: '', completed: false, photoRequired: false },
      { id: 'g-6-3', title: 'Semana 3: completas', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'g-7',
    title: 'Plancha 5 min',
    description: 'Aguanta 5 minutos de plancha al día durante 2 semanas.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 250,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1100,
    icon: '🧱',
    color: '#FC0230',
    images: [],
    tasks: [
      { id: 'g-7-1', title: 'Completar 14 días', description: '5 min de plancha diaria', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'g-8',
    title: 'Peso Muerto Progresivo',
    description: 'Aumenta tu peso en peso muerto semana a semana.',
    category: ChallengeCategory.GYM,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 550,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 420,
    icon: '🏗️',
    color: '#FC0230',
    images: ['https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?w=400'],
    tasks: [
      { id: 'g-8-1', title: 'Semana 1: técnica', description: '', completed: false, photoRequired: true },
      { id: 'g-8-2', title: 'Semana 2: +10%', description: '', completed: false, photoRequired: false },
      { id: 'g-8-3', title: 'Semana 3: +20%', description: '', completed: false, photoRequired: true },
    ],
  },

  // SWIMMING
  {
    id: 's-1',
    title: 'Natación para Principiantes',
    description: 'Nada 500m 3 veces por semana durante un mes.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 350,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 445,
    icon: '🏊',
    color: '#06B6D4',
    images: ['https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=400'],
    tasks: [
      { id: 's-1-1', title: 'Semana 1-2: 12 sesiones', description: '', completed: false, photoRequired: true },
      { id: 's-1-2', title: 'Semana 3-4: 12 sesiones', description: '', completed: false, photoRequired: false },
    ],
  },
  {
    id: 's-2',
    title: 'Estilo Libre 1km',
    description: 'Nada 1km en estilo libre sin parar.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 450,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 310,
    icon: '🌊',
    color: '#06B6D4',
    images: ['https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400'],
    tasks: [
      { id: 's-2-1', title: 'Entrenamiento base', description: '', completed: false, photoRequired: false },
      { id: 's-2-2', title: 'Completar 1km', description: 'Sin parar', completed: false, photoRequired: true },
    ],
  },
  {
    id: 's-3',
    title: 'Mariposa 200m',
    description: 'Aprende y completa 200m de estilo mariposa.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 600,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 180,
    icon: '🦋',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 's-3-1', title: 'Técnica mariposa', description: '', completed: false, photoRequired: false },
      { id: 's-3-2', title: 'Completar 200m', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 's-4',
    title: 'Nado de Resistencia',
    description: '20 sesiones de nado continuo de 45 minutos.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 500,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 260,
    icon: '💧',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 's-4-1', title: '10 sesiones', description: 'Primera mitad', completed: false, photoRequired: true },
      { id: 's-4-2', title: '20 sesiones', description: 'Segunda mitad', completed: false, photoRequired: true },
    ],
  },
  {
    id: 's-5',
    title: 'Cuatro Estilos',
    description: 'Domina los 4 estilos de natación en un mes.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 700,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 140,
    icon: '🔄',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 's-5-1', title: 'Crol y espalda', description: '', completed: false, photoRequired: true },
      { id: 's-5-2', title: 'Braza y mariposa', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 's-6',
    title: 'Agua Abierta 2km',
    description: 'Completa una travesía de 2km en agua abierta.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 750,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 95,
    icon: '🏖️',
    color: '#06B6D4',
    images: ['https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=400'],
    tasks: [
      { id: 's-6-1', title: 'Completar 2km', description: 'Agua abierta', completed: false, photoRequired: true },
    ],
  },
  {
    id: 's-7',
    title: 'Técnica de Salida',
    description: '10 sesiones trabajando la salida y vuelta en natación.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 200,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 380,
    icon: '🎯',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 's-7-1', title: '10 sesiones técnica', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 's-8',
    title: 'Natación Intervalos',
    description: '8 sesiones de natación con intervalos de alta intensidad.',
    category: ChallengeCategory.SWIMMING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 400,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 220,
    icon: '⏩',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 's-8-1', title: '8 sesiones intervalos', description: '', completed: false, photoRequired: true },
    ],
  },

  // YOGA
  {
    id: 'y-1',
    title: 'Yoga Matutino',
    description: 'Practica yoga cada mañana durante 14 días.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 250,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 2341,
    icon: '🧘',
    color: '#10B981',
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400'],
    tasks: [
      { id: 'y-1-1', title: '5 posturas básicas', description: '', completed: false, photoRequired: true },
      { id: 'y-1-2', title: 'Sesión de 20 min', description: '', completed: false, photoRequired: false },
    ],
  },
  {
    id: 'y-2',
    title: 'Estiramientos Diarios',
    description: 'Rutina de 10 minutos de estiramientos durante 7 días.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 200,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1100,
    icon: '🤸',
    color: '#8B5CF6',
    images: [],
    tasks: [
      { id: 'y-2-1', title: 'Completar rutina', description: '10 min de estiramientos', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'y-3',
    title: 'Pilates Core',
    description: 'Fortalece tu core con 20 minutos de pilates diarios.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 280,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1450,
    icon: '🤸‍♀️',
    color: '#10B981',
    images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400'],
    tasks: [
      { id: 'y-3-1', title: 'Semana 1', description: '7 sesiones de pilates', completed: false, photoRequired: true },
      { id: 'y-3-2', title: 'Semana 2', description: '7 sesiones avanzadas', completed: false, photoRequired: false },
    ],
  },
  {
    id: 'y-4',
    title: 'Meditación Activa',
    description: 'Combina 10 min de meditación con 20 min de ejercicio durante 10 días.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 220,
    duration: 10,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1670,
    icon: '🧠',
    color: '#8B5CF6',
    images: [],
    tasks: [
      { id: 'y-4-1', title: 'Completar los 10 días', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'y-5',
    title: 'Yoga Restaurativo',
    description: '7 sesiones de yoga restaurativo para la recuperación.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 180,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 900,
    icon: '🌸',
    color: '#10B981',
    images: [],
    tasks: [
      { id: 'y-5-1', title: '7 sesiones restaurativas', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'y-6',
    title: 'Ashtanga 21 Días',
    description: 'Practica la serie primaria de Ashtanga durante 21 días.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 550,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 430,
    icon: '🌀',
    color: '#10B981',
    images: [],
    tasks: [
      { id: 'y-6-1', title: 'Semana 1', description: 'Serie básica', completed: false, photoRequired: true },
      { id: 'y-6-2', title: 'Semana 2-3', description: 'Serie completa', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'y-7',
    title: 'Respiración Pranayama',
    description: '14 días de práctica de técnicas de respiración.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 160,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 720,
    icon: '💨',
    color: '#10B981',
    images: [],
    tasks: [
      { id: 'y-7-1', title: '14 sesiones pranayama', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'y-8',
    title: 'Yoga para Corredores',
    description: 'Rutina de yoga diseñada para recuperar piernas de corredor.',
    category: ChallengeCategory.YOGA,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 210,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 860,
    icon: '🦶',
    color: '#10B981',
    images: [],
    tasks: [
      { id: 'y-8-1', title: 'Completar 14 sesiones', description: '', completed: false, photoRequired: true },
    ],
  },

  // CYCLING
  {
    id: 'c-1',
    title: 'Ciclismo Urbano',
    description: 'Recorre 100km en bicicleta durante 2 semanas.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 400,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 678,
    icon: '🚴',
    color: '#3B82F6',
    images: ['https://images.unsplash.com/photo-1517649763962-0c623066013b?w=400'],
    tasks: [
      { id: 'c-1-1', title: '0-50km', description: '', completed: false, photoRequired: true },
      { id: 'c-1-2', title: '50-100km', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-2',
    title: 'Gran Fondo 100km',
    description: 'Completa una ruta de 100km en un solo día.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 800,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 220,
    icon: '🏆',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-2-1', title: 'Completar 100km', description: 'En un solo día', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-3',
    title: 'Ciclismo de Montaña',
    description: '3 rutas MTB en un mes.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 600,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 310,
    icon: '⛰️',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-3-1', title: 'Ruta MTB 1', description: '', completed: false, photoRequired: true },
      { id: 'c-3-2', title: 'Ruta MTB 2', description: '', completed: false, photoRequired: true },
      { id: 'c-3-3', title: 'Ruta MTB 3', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-4',
    title: 'Commuter 30 días',
    description: 'Ve al trabajo en bici durante 30 días.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 350,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 540,
    icon: '🏙️',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-4-1', title: '30 días en bici', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-5',
    title: 'Velocidad Promedio 30km/h',
    description: 'Mantén 30km/h de promedio en 5 rutas de 40km.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 700,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 190,
    icon: '💨',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-5-1', title: '5 rutas a 30km/h', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-6',
    title: 'Subida de Puerto',
    description: 'Sube 3 puertos de montaña en bicicleta.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 650,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 155,
    icon: '🚵',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-6-1', title: 'Puerto 1', description: '', completed: false, photoRequired: true },
      { id: 'c-6-2', title: 'Puerto 2', description: '', completed: false, photoRequired: true },
      { id: 'c-6-3', title: 'Puerto 3', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-7',
    title: 'Ruta Costera',
    description: 'Pedalea 60km por la costa en un día.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 450,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 280,
    icon: '🌅',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-7-1', title: 'Completar 60km costera', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'c-8',
    title: 'Spinning 20 Clases',
    description: 'Asiste a 20 clases de spinning en un mes.',
    category: ChallengeCategory.CYCLING,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 300,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 620,
    icon: '🎡',
    color: '#3B82F6',
    images: [],
    tasks: [
      { id: 'c-8-1', title: '20 clases spinning', description: '', completed: false, photoRequired: true },
    ],
  },

  // OUTDOOR
  {
    id: 'o-1',
    title: 'Reto Escalada',
    description: 'Escala al menos 3 rutas distintas en un mes.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 550,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 342,
    icon: '🧗',
    color: '#8B5CF6',
    images: ['https://images.unsplash.com/photo-1503435980610-a51f3ddfee50?w=400'],
    tasks: [
      { id: 'o-1-1', title: 'Ruta 1', description: '', completed: false, photoRequired: true },
      { id: 'o-1-2', title: 'Ruta 2', description: '', completed: false, photoRequired: true },
      { id: 'o-1-3', title: 'Ruta 3', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-2',
    title: 'Senderismo 10km',
    description: 'Realiza una caminata de 10km en montaña.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 320,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 2100,
    icon: '🥾',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1551632811-561732d1e306?w=400'],
    tasks: [
      { id: 'o-2-1', title: 'Completar 10km', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-3',
    title: 'Kayak 5km',
    description: 'Recorre 5km en kayak.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 400,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 210,
    icon: '🚣',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 'o-3-1', title: 'Completar 5km kayak', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-4',
    title: 'Surf 10 sesiones',
    description: '10 sesiones de surf en un mes.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 500,
    duration: 30,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 180,
    icon: '🏄',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 'o-4-1', title: '10 sesiones surf', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-5',
    title: 'Acampada Activa',
    description: 'Acampa y realiza actividades físicas durante 3 días.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 380,
    duration: 3,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 290,
    icon: '⛺',
    color: '#F59E0B',
    images: [],
    tasks: [
      { id: 'o-5-1', title: '3 días acampada activa', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-6',
    title: 'Parkour Urbano',
    description: '8 sesiones de parkour en entorno urbano.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 520,
    duration: 21,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 140,
    icon: '🏙️',
    color: '#8B5CF6',
    images: [],
    tasks: [
      { id: 'o-6-1', title: '8 sesiones parkour', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-7',
    title: 'Paracaidismo',
    description: 'Completa tu primer salto en paracaídas.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 1000,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 65,
    icon: '🪂',
    color: '#8B5CF6',
    images: [],
    tasks: [
      { id: 'o-7-1', title: 'Salto paracaídas', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'o-8',
    title: 'Rafting Nivel 3',
    description: 'Completa un recorrido de rafting nivel 3.',
    category: ChallengeCategory.OUTDOOR,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 480,
    duration: 1,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 160,
    icon: '🌊',
    color: '#06B6D4',
    images: [],
    tasks: [
      { id: 'o-8-1', title: 'Completar rafting', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-1',
    title: 'Paseo matutino con el perro',
    description: 'Sal a caminar al menos 30 minutos con tu perro antes de las 9am.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 200,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1850,
    icon: '🐕',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400'],
    tasks: [
      { id: 'p-1-1', title: 'Foto en el paseo matutino', description: 'Tú y tu perro en el paseo', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-2',
    title: 'Foto con un Labrador',
    description: 'Encuentra y fotografíate con un Labrador Retriever.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 150,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1230,
    icon: '🦮',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1560807707-8cc77767d783?w=400'],
    tasks: [
      { id: 'p-2-1', title: 'Foto con un Labrador', description: 'Tú junto a un Labrador Retriever', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-3',
    title: 'Corre con tu perro',
    description: 'Completa una carrera de al menos 3km con tu perro como compañero.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 350,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 940,
    icon: '🏃',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400'],
    tasks: [
      { id: 'p-3-1', title: 'Foto corriendo con tu perro', description: 'En plena carrera juntos', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-4',
    title: 'Abrazo con un gato',
    description: 'Captura un momento de cariño abrazando a un gato.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 120,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 2100,
    icon: '🐱',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400'],
    tasks: [
      { id: 'p-4-1', title: 'Foto abrazando un gato', description: 'Un momento de ternura felina', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-5',
    title: 'Trote en el parque canino',
    description: 'Lleva a tu perro al parque canino y troten juntos por 20 minutos.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 280,
    duration: 5,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 720,
    icon: '🌳',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400'],
    tasks: [
      { id: 'p-5-1', title: 'Foto trotando en el parque', description: 'Tu perro y tú en el parque canino', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-6',
    title: 'Foto con 3 razas distintas',
    description: 'Fotografíate con perros de 3 razas completamente diferentes.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.INTERMEDIATE,
    points: 300,
    duration: 14,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 580,
    icon: '🐶',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?w=400'],
    tasks: [
      { id: 'p-6-1', title: 'Foto con raza 1', description: '', completed: false, photoRequired: true },
      { id: 'p-6-2', title: 'Foto con raza 2', description: '', completed: false, photoRequired: true },
      { id: 'p-6-3', title: 'Foto con raza 3', description: '', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-7',
    title: 'Entrenamiento con mascota',
    description: 'Haz una sesión de ejercicio en casa mientras tu mascota te acompaña.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.BEGINNER,
    points: 180,
    duration: 3,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 1340,
    icon: '🏠',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1601758124510-52d02ddb7cbd?w=400'],
    tasks: [
      { id: 'p-7-1', title: 'Foto entrenando con tu mascota', description: 'Ejercicio en casa acompañado', completed: false, photoRequired: true },
    ],
  },
  {
    id: 'p-8',
    title: 'Selfie con mascota en ruta',
    description: 'Hazte una selfie con tu mascota en el punto más alto de tu ruta.',
    category: ChallengeCategory.PETS,
    difficulty: ChallengeDifficulty.ADVANCED,
    points: 400,
    duration: 7,
    status: ChallengeStatus.NOT_STARTED,
    progress: 0,
    participants: 430,
    icon: '🤳',
    color: '#F59E0B',
    images: ['https://images.unsplash.com/photo-1551717743-49959800b1f6?w=400'],
    tasks: [
      { id: 'p-8-1', title: 'Selfie en el punto más alto', description: 'Tú y tu mascota en la cima', completed: false, photoRequired: true },
    ],
  }
];

// ─── Tableros temáticos ──────────────────────────────────────────────────────
// Cada tablero toma exactamente 8 retos de la misma categoría

export interface ThemedBoard {
  id: string;
  title: string;
  emoji: string;
  color: string;
  challenges: Challenge[];
  coverImage?: string;
  description?: string;
  active?: boolean;
}

export const THEMED_BOARDS: ThemedBoard[] = [
  {
    id: 'board-running',
    title: 'Running',
    emoji: '🏃',
    color: '#FF5327',
    challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.RUNNING).slice(0, 8),
  },
  {
    id: 'board-gym',
    title: 'Gym & Fuerza',
    emoji: '💪',
    color: '#FC0230',
    challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.GYM).slice(0, 8),
  },
  {
    id: 'board-swimming',
    title: 'Natación',
    emoji: '🏊',
    color: '#06B6D4',
    challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.SWIMMING).slice(0, 8),
  },
  {
    id: 'board-yoga',
    title: 'Yoga & Mente',
    emoji: '🧘',
    color: '#10B981',
    challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.YOGA).slice(0, 8),
  },
  {
    id: 'board-cycling',
    title: 'Ciclismo',
    emoji: '🚴',
    color: '#3B82F6',
    challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.CYCLING).slice(0, 8),
  },
  {
    id: 'board-outdoor',
    title: 'Outdoor',
    emoji: '🧗',
    color: '#8B5CF6',
    challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.OUTDOOR).slice(0, 8),
  },
  {
  id: 'board-pets',
  title: 'Mascotas',
  emoji: '🐾',
  color: '#F59E0B',
  challenges: ALL_CHALLENGES.filter(c => c.category === ChallengeCategory.PETS).slice(0, 8),
},
];

// Primer tablero por defecto (lo que carga HomePage al inicio)
export const mockChallenges = THEMED_BOARDS[0].challenges;
export const mockChallengesBoard2 = THEMED_BOARDS[1].challenges;

// ─── Notificaciones ──────────────────────────────────────────────────────────

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: '¡Nuevo Reto Disponible!',
    message: 'El reto "30 Días de Running" acaba de ser publicado',
    type: 'challenge',
    read: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    actionUrl: '/challenges/1',
  },
  {
    id: '2',
    title: '¡Felicidades!',
    message: 'Has ganado la insignia "Corredor Inicial"',
    type: 'success',
    read: false,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: '3',
    title: 'Recordatorio',
    message: 'No olvides completar tu entrenamiento de hoy',
    type: 'info',
    read: true,
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
];
